require('config.colorscheme')
require('config.lsp')
require('config.ui')

require('config.colorizer')
require('config.comment')
require('config.flash')
require('config.impatient')
require('config.leap')
require('config.illuminate')
require('config.nulls')
require('config.surround')
require('config.treesitter')
